### ISSUE TITLE
Executing Twitter.login causes an ECONNREFUSED error

### ISSUE THREAD

**Issue by thewh1teagle** [book000/twitterts#1175]
```
import {Twitter} from '@book000/twitterts'

const username = 'username'
const password = 'password'
// const emailAddress = 'email'
const twitter = await Twitter.login({username, password,puppeteerOptions: {userDataDirectory: '.user-data'}})
```

```console
[2024-09-30 07:21:35.817] [main/ERROR]: uncaughtException ({"code":"ECONNREFUSED"})
```

Why does it tries to connect MySQL? I don't want to use MySQL.

**Comment by book000** [comment]
@thewh1teagle, Thank you for creating the issue.
I'm sorry. The error you pointed out seems to be a bug.

The library implements a mechanism to save the response to the DB for automatic response type generation.
Normally, this should not be saved unless explicitly enabled, but it seems that it is not implemented as expected.

I will try to fix this as soon as possible, so please be patient!

**Comment by thewh1teagle** [comment]
@book000 

Thanks!

By the way, I'm curious. I would like to collect all of my `posts` and `replies` (posts,replies,reposts,quotes)
Does it possible with this library? 
In addition, I haven't looked into the library yet, but does it it scraping the DOM or it's work more efficient by doing lightweight http requests once the login succeed?

**Comment by book000** [comment]
Hi @thewh1teagle,
This library is achieved by manipulating the Chrome browser to actually access `x.com` and intercepting the API responses as they are communicated in the background.
This is a way to prevent banning, etc. as much as possible by handling the process in the same way as it is actually done in the browser.

If you prefer to simplify with a single HTTP request after login, we also recommend something like [trevorhobenshield/twitter-api-client](https://github.com/trevorhobenshield/twitter-api-client).

Regarding your expectation of the requirement to retrieve all of one's posts, this library may not be able to meet it.
This is because I remember that the Twitter user page does not allow you to go back more than 3200 tweets.

An official Twitter feature, the download feature, might be useful.
https://help.x.com/en/managing-your-account/how-to-download-your-x-archive

**Comment by book000** [comment]
fixed by https://github.com/book000/twitterts/pull/1176
